/**
 * icuasw_mmesp_project_template.ts
 * Plantilla para generar el archivo principal (.cpp) del proyecto EDROOM.
 * Genera las inclusiones, instancias y configuración de los componentes para el despliegue.
 */
import type { Node, NodeData } from '../../components/types';

/**
 * Clase que encapsula la generación del archivo principal del proyecto EDROOM.
 */
export class icuasw_mmesp_project_template {
    /**
     * Genera el contenido del archivo principal (.cpp) para el nodo lógico.
     * @param nodes - Nodos del diagrama.
     * @param localNodeName - Nombre del nodo local.
     * @returns Código fuente .cpp generado.
     */
    public static generateMainFileContent(nodes: Node<NodeData>[], localNodeName: string): string {

        // Generar inclusiones de cabeceras
        const includes = nodes.map(c => {
            const name = c.data.name.replace(/\s/g, '').toLowerCase();
            const prefix = this.getIncludePrefix(c, localNodeName);
            return `#include <public/${prefix}${name}_iface_v1.h>`;
        }).join('\n');

        // Generar las instancias de los componentes
        const initComponents = nodes.map(c => {
            const id = c.data.componentId;
            const maxMessages = c.data.maxMessages;
            const priority = c.data.priority;
            const stackSize = c.data.stackSize;
            const componentClass = this.getComponentClass(c, localNodeName);
            const finalInstanceName = this.getInstanceName(c, localNodeName);
            const memoryName = this.getInstanceName(c, localNodeName);

            return `\t${componentClass}  ${finalInstanceName}(${id}, ${maxMessages}, ${priority}, ${stackSize}, systemDeployment.Get${memoryName}Memory());`;
        }).join('\n');
        
        // Generar la lista de componentes para la configuración
        const configComponents = nodes.map(c => {
            const instanceName = this.getInstanceName(c, localNodeName);
            return `&${instanceName}`;
        }).join(', ');

        return `//##############################################################################
//###############    This file has been generated by Connectus    ###############
//##############################################################################

#include <public/edroom_glue.h>


//******************************************************************************
// include deployment edroom components
${includes}

#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK

    CEDROOMSystemDeployment systemDeployment;

#endif


rtems_task Init (uint32_t arg){

    //uint32_t aux;

#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK

    CEDROOMSystemDeployment systemDeployment;

#endif

    //aux=sizeof(systemDeployment) + sizeof(ICUASW)+   sizeof(CCEPDManager);
    //aux+= sizeof(CCTM_ChannelCtrl) +sizeof(RCCHK_FDIRMng) +sizeof(RCCBKGTCExec);

${initComponents}

    //if(aux< 32*1024){
    systemDeployment.Config(${configComponents});

    systemDeployment.Start();
    //}
    //;

}`;
    }

    // --- Funciones auxiliares para la lógica de la plantilla ---

    /**
     * Obtiene el nombre de instancia para un nodo dado.
     * @param node - Nodo del diagrama.
     * @param localNodeName - Nombre del nodo local.
     * @returns Nombre de instancia.
     */
    private static getInstanceName(node: Node<NodeData>, localNodeName: string): string {
        const isRemote = node.data.node !== localNodeName;
        const componentNameBase = node.data.name.toLowerCase().replace(/\s/g, '');
        
        if (isRemote) {
            return `r${componentNameBase}`;
        }
        return componentNameBase;
    }

    /**
     * Obtiene la clase de componente para un nodo.
     * @param node - Nodo del diagrama.
     * @param localNodeName - Nombre del nodo local.
     * @returns Nombre de la clase de componente.
     */
    private static getComponentClass(node: Node<NodeData>, localNodeName: string): string {
        const isRemote = node.data.node !== localNodeName;
        const componentType = node.data.name.replace(/\s/g, '');

        if (node.data.isTop && isRemote) {
            return `R${componentType}`;
        } else if (node.data.isTop && !isRemote) {
            return componentType;
        } else if (!node.data.isTop && isRemote) {
            return `RCC${componentType}`;
        } else { // !node.data.isTop && !isRemote
            return `CC${componentType}`;
        }
    }

    /**
     * Obtiene el prefijo de inclusión para un nodo.
     * @param node - Nodo del diagrama.
     * @param localNodeName - Nombre del nodo local.
     * @returns Prefijo para el include.
     */
    private static getIncludePrefix(node: Node<NodeData>, localNodeName: string): string {
        const isRemote = node.data.node !== localNodeName;
        
        if (node.data.isTop && isRemote) {
            return 'r';
        } else if (node.data.isTop && !isRemote) {
            return '';
        } else if (!node.data.isTop && isRemote) {
            return 'rcc';
        } else { // !node.data.isTop && !isRemote
            return 'cc';
        }
    }
}