@startuml
start

:Usuario abre la aplicación;
:Usuario crea un componente;
:Usuario edita atributos del componente;
:Usuario añade puertos al componente;
:Usuario crea otro componente;
:Usuario conecta puertos entre componentes;

stop
@enduml